/**
 * Seam: Zod <-> Pydantic JSON Schema parity (Sprint 001, D-19).
 *
 * `src/schema.json` is generated by `services/engine/scripts/export_schema.py` from the Pydantic
 * mirrors. This test renders each Zod schema to JSON Schema, applies the same canonical form the
 * exporter applies, and requires deep equality. Any field, bound or enum that drifts on either
 * side fails here.
 */
import { describe, expect, it } from "vitest";
import { z } from "zod";

import {
  AdminDecision,
  Bid,
  BidCreate,
  Booking,
  BookingCreate,
  BookingProposal,
  BuilderProfile,
  Candidate,
  ChatResponse,
  ChatTurn,
  Credential,
  CredentialInput,
  Dashboard,
  DecidedQueue,
  Eligibility,
  Ecosystem,
  Gap,
  PendingQueue,
  PendingShowcase,
  DecidedShowcase,
  ProfileInput,
  Project,
  ProjectInput,
  ReasoningPath,
  Request,
  RequestCreate,
  RoleResponse,
  ShowcaseCard,
  ShowcaseDetail,
  ShowcaseEdit,
  ShowcasePage,
  ShowcaseProject,
  SkillSuggestRequest,
  SkillSuggestions,
  VentureBrief,
  VentureRoute,
} from "../src/index.js";
import exported from "../src/schema.json" with { type: "json" };

type Json = { [key: string]: unknown };

const DECORATION_KEYWORDS = new Set(["title", "description", "discriminator", "$schema"]);

/** Same rules as `export_schema.canonical`: strip decoration, sort `required`, keep property maps. */
function canonical(schema: unknown): unknown {
  if (Array.isArray(schema)) return schema.map(canonical);
  if (schema === null || typeof schema !== "object") return schema;
  let source = schema as Json;
  // Zod writes an unconstrained nullable primitive as `type: [T, "null"]`; Pydantic writes the
  // equivalent `anyOf`. Both sides canonicalise to the `anyOf` form.
  if (Array.isArray(source["type"])) {
    const { type, ...rest } = source;
    source = { ...rest, anyOf: (type as string[]).map((t) => ({ type: t })) };
  }
  const out: Json = {};
  for (const key of Object.keys(source).sort()) {
    const value = source[key];
    if (DECORATION_KEYWORDS.has(key)) continue;
    // Zod restates `format: "date"` / `"date-time"` as a regex; the format keyword is the contract.
    if (key === "pattern" && (source["format"] === "date" || source["format"] === "date-time")) continue;
    if (key === "properties") {
      const props: Json = {};
      for (const name of Object.keys(value as Json).sort()) props[name] = canonical((value as Json)[name]);
      out[key] = props;
    } else if (key === "required") {
      out[key] = [...(value as string[])].sort();
    } else {
      out[key] = canonical(value);
    }
  }
  return out;
}

const cases: [keyof typeof exported, z.ZodType][] = [
  ["VentureBrief", VentureBrief],
  ["VentureRoute", VentureRoute],
  ["ChatTurn", ChatTurn],
  ["ChatResponse", ChatResponse],
  ["ReasoningPath", ReasoningPath],
  ["Gap", Gap],
  ["Ecosystem", Ecosystem],
  ["ProfileInput", ProfileInput],
  ["BuilderProfile", BuilderProfile],
  ["RoleResponse", RoleResponse],
  ["CredentialInput", CredentialInput],
  ["Credential", Credential],
  ["ProjectInput", ProjectInput],
  ["Project", Project],
  ["PendingQueue", PendingQueue],
  ["DecidedQueue", DecidedQueue],
  // Sprint 005a admin card preview (spec #86 story 48), registered on their own too.
  ["PendingShowcase", PendingShowcase],
  ["DecidedShowcase", DecidedShowcase],
  ["AdminDecision", AdminDecision],
  ["Candidate", Candidate],
  // Sprint 004 (#54): requests, bids, bookings, eligibility, dashboard.
  ["RequestCreate", RequestCreate],
  ["Request", Request],
  ["BidCreate", BidCreate],
  ["Bid", Bid],
  ["BookingCreate", BookingCreate],
  ["BookingProposal", BookingProposal],
  ["Booking", Booking],
  ["Eligibility", Eligibility],
  ["Dashboard", Dashboard],
  // Sprint 005a (#86): showcase and skill suggestion contracts.
  ["ShowcaseCard", ShowcaseCard],
  ["ShowcaseDetail", ShowcaseDetail],
  ["ShowcaseEdit", ShowcaseEdit],
  ["ShowcasePage", ShowcasePage],
  ["ShowcaseProject", ShowcaseProject],
  ["SkillSuggestRequest", SkillSuggestRequest],
  ["SkillSuggestions", SkillSuggestions],
];

describe("Zod JSON Schema equals Pydantic JSON Schema", () => {
  it.each(cases)("%s", (name, schema) => {
    const fromZod = canonical(z.toJSONSchema(schema, { io: "input" }));
    const fromPydantic = canonical(exported[name]);
    expect(fromZod).toEqual(fromPydantic);
  });

  it("exports every contract the engine exports, and nothing else", () => {
    expect(cases.map(([name]) => name).sort()).toEqual(Object.keys(exported).sort());
  });
});
