#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# Venture Route deploy (D-57, #138). docs/DEPLOY.md is the readable source; this script walks
# the same steps in the same order: Render, then Vercel, then connect, then verify. It never
# echoes, stores or writes a secret: secrets go straight into the dashboard or the CLI prompt,
# or are read with `read -rs` inside a subshell that exits after one command. Only public
# values (the two URLs and the Render service id) are captured, in shell variables, never in a
# file: the library's write_env is deliberately unused. Run from the repo root in Git Bash
# (Windows) or any bash.

TOTAL_STAGES=15

# show_cmd prints a command for the human to see.
show_cmd() { printf '    %s$ %s%s\n' "$BOLD" "$1" "$RESET"; }

# run_cmd "cmd" shows a command and, after a y/N gate, runs it here. Failure warns, never aborts.
run_cmd() {
  show_cmd "$1"
  if confirm "Run it now?"; then
    bash -c "$1" || warn "command exited non-zero; read the output above before going on"
  else
    note "skipped; run it yourself in another terminal"
  fi
}

# paste_back "what" says what to copy into the agent chat (never a secret).
paste_back() { printf '\n  %s%sPaste back to the agent:%s %s\n' "$BOLD" "$GREEN" "$RESET" "$1"; }

cd "$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
if [[ ! -f render.yaml || ! -f apps/web/vercel.json ]]; then
  warn "run this from the Venture Route repo"
  exit 1
fi

ENGINE_URL=""; WEB_URL=""; SRV_ID=""
VERCEL_SCOPE="simplenjenga4-6645s-projects"
VERCEL_PROJECT="basix-venture-route"

banner "Venture Route deploy: Render engine + Vercel web"

# ── 0. Prerequisites ─────────────────────────────────────────────────────
stage "Prerequisites: CLIs and log-ins"
say "Install if missing (docs/DEPLOY.md section 0.1):"
step "Render CLI: winget install Render.CLI, or the release zip from github.com/render-oss/cli/releases"
step "            (macOS/Linux: brew install render-oss/render/render)"
step "Vercel CLI: npm i -g vercel"
if command -v render >/dev/null 2>&1; then note "render found"; else warn "render CLI not on PATH"; fi
if command -v vercel >/dev/null 2>&1; then note "vercel found"; else warn "vercel CLI not on PATH"; fi
say "Log in to both (each opens a browser):"
run_cmd "render login"
run_cmd "render workspace set"
run_cmd "vercel login"
say "Have ready in your password manager (section 0.3): Neon production pooled and direct URLs in"
say "the asyncpg form (postgresql+asyncpg://...?ssl=require), Clerk JWKS URL, sk_test, pk_test,"
say "the Anthropic and OpenRouter keys, ADMIN_EMAILS."
pause "Press Enter when both CLIs are logged in"

stage "Render: validate the Blueprint"
say "Render deploys render.yaml from master, so it must be merged first."
run_cmd "git fetch origin && git show origin/master:render.yaml >/dev/null && echo 'render.yaml is on master'"
run_cmd "render blueprints validate render.yaml"
paste_back "the last lines of 'render blueprints validate'"
pause

# ── 2. Render ────────────────────────────────────────────────────────────
stage "Render: apply the Blueprint (dashboard)"
open_url "https://dashboard.render.com/blueprints"
step "New Blueprint Instance: connect simpleHacker0893/basix-venture-route, branch master."
step "Render shows one web service, venture-route-engine (Docker, Ohio, Starter)."
step "Type each prompted value into the browser (docs/DEPLOY.md section 1.2):"
note "  DATABASE_URL (pooled), DATABASE_URL_DIRECT, ANTHROPIC_API_KEY, OPENROUTER_API_KEY,"
note "  CLERK_JWKS_URL, CLERK_SECRET_KEY, ADMIN_EMAILS,"
note "  CLERK_WEBHOOK_SIGNING_SECRET = whsec_replace-me (the real one comes in a later stage),"
note "  CORS_ORIGINS = http://localhost:5173,http://localhost:4173 (Vercel origin added later)."
step "Click Apply and wait for the first build (several minutes)."
ask ENGINE_URL "Paste the service URL (https://venture-route-engine-....onrender.com):"
ENGINE_URL="${ENGINE_URL%/}"
paste_back "$ENGINE_URL"
pause

stage "Render: service id and first deploy"
run_cmd "render services -o json"
ask SRV_ID "Paste the srv-... id of venture-route-engine:"
run_cmd "render deploys list $SRV_ID"
say "Tail the logs until 'Application startup complete', then Ctrl-C:"
run_cmd "render logs -r $SRV_ID --tail"
paste_back "the srv id, the top 'render deploys list' line (live) and any ERROR or Traceback line"
pause

stage "Render: migration (free plan only)"
say "On Starter the pre-deploy command already ran 'alembic upgrade head': answer N."
if confirm "Are you on the FREE plan (no pre-deploy command)?"; then
  say "Paste the Neon DIRECT URL at the hidden prompt; it lives only in a subshell."
  (
    cd services/engine
    printf '  Neon direct URL (hidden): '
    read -rs ALEMBIC_DATABASE_URL
    printf '\n'
    export ALEMBIC_DATABASE_URL
    uv run python -m alembic upgrade head
  ) || warn "migration failed; read the output above"
  paste_back "the last 'Running upgrade' line, or no error"
  pause
fi

stage "Render: health check"
show_cmd "curl -s $ENGINE_URL/health"
curl -s --max-time 90 "$ENGINE_URL/health" || warn "no answer; check: render logs -r $SRV_ID"
printf '\n'
note "Expect \"status\":\"ok\" and \"demo_today\":\"2026-09-22\"."
paste_back "the JSON line above"
pause

# ── 3. Vercel ────────────────────────────────────────────────────────────
stage "Vercel: Root Directory = apps/web (fixes the preview check)"
say "Root cause: the project builds from the repo root (rootDirectory null), never reads"
say "apps/web/vercel.json, and fails with: No Output Directory named \"public\" found."
open_url "https://vercel.com/$VERCEL_SCOPE/$VERCEL_PROJECT/settings/build-and-deployment"
step "Root Directory: apps/web, then Save."
step "Keep 'Include files outside the root directory in the Build Step' ON."
step "Leave Framework Preset and the Build/Output/Install overrides OFF (vercel.json sets them)."
paste_back "Root Directory = apps/web"
pause

stage "Vercel: link the repo root to the project"
run_cmd "vercel link --project $VERCEL_PROJECT --scope $VERCEL_SCOPE"
note "Answer no to any offer to override build settings."
paste_back "the 'Linked to ...' line"
pause

stage "Vercel: the four VITE_* variables, Production and Preview"
say "Each command prompts for the value; for Preview press Enter at the branch question."
note "VITE_API_URL = $ENGINE_URL"
note "VITE_CLERK_PUBLISHABLE_KEY = pk_test_...   VITE_OFFLINE_DEMO = 0   VITE_VOICE_PROVIDER = web"
warn "Never add an engine variable (DATABASE_URL, CLERK_SECRET_KEY, *_API_KEY) to Vercel."
for name in VITE_API_URL VITE_CLERK_PUBLISHABLE_KEY VITE_OFFLINE_DEMO VITE_VOICE_PROVIDER; do
  for target in production preview; do
    run_cmd "vercel env add $name $target"
  done
done
run_cmd "vercel env ls"
paste_back "the 'vercel env ls' table (values show as Encrypted)"
pause

stage "Vercel: first production deploy"
note "Git is already connected (production branch master). Run 'vercel git connect' only if"
note "Settings, Git shows no repository."
run_cmd "vercel --prod"
ask WEB_URL "Paste the Aliased production URL (https://....vercel.app):"
WEB_URL="${WEB_URL%/}"
paste_back "$WEB_URL"
pause

# ── 4. Connect ───────────────────────────────────────────────────────────
stage "Connect: CORS_ORIGINS on Render"
open_url "https://dashboard.render.com"
step "venture-route-engine, Environment, CORS_ORIGINS, Edit. Set exactly:"
show_cmd "$WEB_URL,http://localhost:5173,http://localhost:4173"
step "Save, rebuild and deploy. Wait for it to go live."
pause "Press Enter once the redeploy is live"
show_cmd "curl -i -H \"Origin: $WEB_URL\" $ENGINE_URL/health"
curl -si --max-time 90 -H "Origin: $WEB_URL" "$ENGINE_URL/health" | grep -iE '^(HTTP/|access-control-allow-)' || warn "no CORS headers"
note "Expect: access-control-allow-origin: $WEB_URL"
paste_back "the header lines above"
pause

stage "Connect: Clerk webhook"
open_url "https://dashboard.clerk.com"
step "Venture Route, Development, Webhooks, Add Endpoint."
step "URL: $ENGINE_URL/api/webhooks/clerk"
step "Events: user.created and user.updated only, then Create."
step "Reveal the Signing Secret (whsec_...) and paste it on Render as CLERK_WEBHOOK_SIGNING_SECRET,"
step "then Save, rebuild and deploy. Do not use Clerk's 'Send example' (it writes a fake user)."
paste_back "'webhook created' and the endpoint URL (no secret)"
pause

stage "Connect: Clerk allowed origin and session token"
say "Adds $WEB_URL to the instance's allowed_origins through the Backend API (check the field"
say "against Clerk's Backend API reference first). The secret key is read hidden, in a subshell."
if confirm "Send the PATCH now?"; then
  (
    printf '  CLERK_SECRET_KEY (hidden): '
    read -rs CLERK_SECRET_KEY
    printf '\n'
    curl -s -X PATCH https://api.clerk.com/v1/instance \
      -H "Authorization: Bearer $CLERK_SECRET_KEY" -H "Content-Type: application/json" \
      -d "{\"allowed_origins\":[\"$WEB_URL\",\"http://localhost:5173\"]}" \
      -o /dev/null -w '  HTTP %{http_code}\n'
  ) || warn "request failed"
fi
step "Check only: Sessions, Customize session token contains:"
show_cmd '{"metadata": "{{user.public_metadata}}"}'
paste_back "the HTTP status and 'metadata claim present'"
pause

stage "Connect: Showcase seed on Neon production (once)"
say "Idempotent; writes only demo_data rows. Paste the Neon production POOLED URL at the hidden prompt."
if confirm "Seed now?"; then
  (
    cd services/engine
    printf '  Neon pooled URL (hidden): '
    read -rs DATABASE_URL
    printf '\n'
    export DATABASE_URL
    uv run python scripts/seed_showcase_demo.py
  ) || warn "seed failed; read the output above"
  run_cmd "render restart $SRV_ID"
fi
paste_back "the '[showcase seed] ...' line and projected_rows from /health after the restart"
pause

# ── 5. Verify ────────────────────────────────────────────────────────────
stage "Verify"
show_cmd "curl -s $ENGINE_URL/health"
curl -s --max-time 90 "$ENGINE_URL/health" || warn "no answer"
printf '\n'
show_cmd "curl -i -X OPTIONS $ENGINE_URL/api/route   (preflight from $WEB_URL)"
curl -si --max-time 90 -X OPTIONS "$ENGINE_URL/api/route" \
  -H "Origin: $WEB_URL" -H "Access-Control-Request-Method: POST" \
  -H "Access-Control-Request-Headers: content-type,authorization" \
  | grep -iE '^(HTTP/|access-control-allow-)' || warn "no CORS headers"
open_url "$WEB_URL"
step "Route the Health pilot scenario; refresh $WEB_URL/showcase (it loads and lists the seed)."
step "Sign up with a fresh email, pick a role, reach the dashboard."
step "Clerk, Webhooks, the endpoint, Message Attempts: user.created shows 200."
paste_back "the health JSON, the preflight headers, and 'scenario / sign-in / webhook 200 / showcase OK'"
pause

finish
note "Engine: $ENGINE_URL"
note "Web:    $WEB_URL"
note "Render service: $SRV_ID"
note "Rollback and free-plan notes: docs/DEPLOY.md sections 6 and 7."
printf '\n'
